const ADD_TOAST = 'ADD_TOAST';
const ADD_TOAST_SUCCESS = 'ADD_TOAST_SUCCESS';
const REMOVE_TOAST = 'REMOVE_TOAST';
const REMOVE_TOAST_SUCCESS = 'REMOVE_TOAST_SUCCESS';

export { ADD_TOAST, ADD_TOAST_SUCCESS, REMOVE_TOAST, REMOVE_TOAST_SUCCESS };
