const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE';

export { FETCH_TODO_REQUEST, FETCH_TODO_SUCCESS, FETCH_TODO_FAILURE };
